name: Job
version: '${project.version}'
main: fr.tiltech.job.Main
api-version: 1.19
description: Plugin job
commands:
  test:
    description: Test command
  jpr:
    description: reload plugin
    permission: jobplugin.reload