name: JobPlugin
version: '${project.version}'
main: fr.tiltech.job.Job
api-version: 1.19
description: Plugin job
commands:
  test:
    description: Test command
  jpr:
    description: reload plugin
    permission: jobplugin.reload
  jobs:
    description: show all available jobs
    permission: jobplugin.jobss
    aliases: [j]
    usage: /<command>
  job:
    description: use this command with an argument (a job)
    permission: jobplugin.job